# Generated by Django 5.2.6 on 2025-12-12 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AjiraApp', '0006_alter_contactmessage_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='DravTech Marketplace', max_length=200)),
                ('site_email', models.EmailField(default='admin@dravtech.com', max_length=254)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('currency_symbol', models.CharField(default='$', max_length=5)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configuration',
            },
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='category_type',
            field=models.CharField(max_length=100, verbose_name='Category Type'),
        ),
        migrations.AlterUniqueTogether(
            name='productcategory',
            unique_together={('name', 'category_type')},
        ),
    ]
