# Generated by Django 5.2.6 on 2025-12-12 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AjiraApp', '0007_siteconfig_alter_productcategory_category_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(help_text='Download or Visit URL')),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='apps/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
